# Generated by Django 6.0.4 on 2026-04-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('kode_maskapai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_maskapai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maskapai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('salutation', models.CharField(max_length=10)),
                ('first_mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id_tier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('minimal_frekuensi_terbang', models.IntegerField()),
                ('minimal_tier_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'tier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('nomor_member', models.CharField(max_length=20, unique=True)),
                ('tanggal_bergabung', models.DateField()),
                ('award_miles', models.IntegerField(blank=True, null=True)),
                ('total_miles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.pengguna')),
                ('id_staf', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'staf',
                'managed': False,
            },
        ),
    ]
